embedding_model_name = "qwen3-embedding-0.6b"
chat_model_name = "qwen3-4b"
top_k = 3
retrieval_candidate_k = 10
min_score_threshold = 0.55
min_confidence_score = 0.60
relative_score_ratio = 0.90
bm25_weight = 0.5
semantic_weight = 0.5# Cross-encoder re-ranking (using a public model for re-ranking)
enable_reranker = True
cross_encoder_model = "cross-encoder/qnli-distilroberta-base"